name: Build and Test
 
on:
  push:
    branches-ignore:
      - 'master'
      - 'main'
      - 'develop'
 
jobs:
  build_and_test:
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Build
        run: mvn -DskipTests -B clean package
      - name: Test
        run: mvn -B test
        